svr_config:
    name: "videosvr"
    host: "106.53.162.149"
    port: 8004
    relation_svr_name: "relationsvr"
    favorite_svr_name: "favoritesvr"
    machine_id: 1

redis:
  host: "106.53.162.149"
  password: ""
  db: 0
  port: 6379
  PoolSize: 10

mysql:
  host: "106.53.162.149"
  port: "8086"
  database: "camps_tiktok"
  username: "root"
  password: "123456"
  max_idle_conn: 10
  max_open_conn: 100
  max_idle_time: 30

log:
  level: "debug"
  file_name: "video.log"
  log_path: "../../log/videosvr/"
  max_size: 200
  max_age: 30
  max_backups: 7

consul:
  host: "106.53.162.149"
  port: 8500
  tags:
    - "videosvr"

minio:
  host: "106.53.162.149"
  port: "9000"
  access_key_id: "J7F9PEAVuVMEi0siA5XA"
  secret_access_key: "3ZdSIgpxYsWadxWV4Ngp267vxfO5DvklVV42QxrP"
  video_buckets: video
  pic_buckets: pic
  video_path: "/root/tiktok/video"
  pic_path: "/root/tiktok/pic"

